### ISSUE TITLE
cuDNN error:CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by zhangpj** [tonyngjichun/SOLAR#4]
Hi, thank you for sharing this project. Good job! I tried to run this project, but I met some questions.
1. When I run `python3 create_db_pickle.py`, the logs are as follow:
![pickle](https://user-images.githubusercontent.com/20679750/95802063-fd0bd580-0d2e-11eb-9c13-457ff71b6c8a.png)
Is the number of training images and val images correct?
2 I meet a problem when training:
![problem](https://user-images.githubusercontent.com/20679750/95802073-0301b680-0d2f-11eb-87ee-3031cab38824.png)
Have you ever had a similar problem? I try to decrease batch size, but it doesn't work for me.
Can you tell me what is the specific version of pytorch, cuda and cudnn you use?

**Comment by tonyngjichun** [comment]
Hi, sorry for the delayed response. This seems to be a weird PyTorch thing that some tensors deemed contiguous in certain versions are not contiguous in a different version. I tested on PyTorch 1.4 and cuda 10.1 and it works fine. Could you pleas try calling `.contiguous()` in the tensors within the training script and create a PR once you've found which line is causing the problem?

Thanks and apologies again for the late response!

**Comment by zhangpj** [comment]
@tonyngjichun Thanks for your response. I have solved this problem after updating PyTorch.
